*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x8111e830

System: Linux guo-Inspiron-7557 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

ViZDoom version 1.1.3 (ZDOOM 2.8.1) ()
Compiler version: 4.9.3

Command line: /usr/local/lib/python2.7/dist-packages/vizdoom/vizdoom -iwad /usr/local/lib/python2.7/dist-packages/vizdoom/freedoom2.wad -config _vizdoom.ini +map map01 -skill 3 -width 640 -height 480 +vid_aspect 3 +fullscreen 0 +viz_controlled 1 +viz_instance_id FTpDS8zYpD +use_mouse 0 -rngseed 1465590513 +viz_render_mode 3661 +viz_noconsole 1 +viz_screen_format 0 +viz_window_hidden 1 +viz_noxserver 1 -noidle -nojoy -nosound +viz_nosound 1 -host 1 -deathmatch +timelimit 1.0 +sv_forcerespawn 1 +sv_noautoaim 1 +sv_respawnprotect 1 +sv_spawnfarthest 1 +name AI +colorset 0 -file map/cig_custom.wad

Wad 0: vizdoom.pk3
Wad 1: freedoom2.wad
Wad 2: cig_custom.wad

Not in a level.

Executing: gdb --quiet --batch --command=gdb-respfile-XFQQq8
